default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails42_arel_val_error_development

test:
  <<: *default
  database: rails42_arel_val_error_test
